trigger:
- master

pool: MOSHE
jobs:
  - job: 
    steps:
    - script: git clone --branch master https://github.com/moshe322/docker-maven-sample.git
    
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: 'default'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
  - job:
    steps:
    - script: 
      displayName: echo Docker Build
    - task: Docker@2
      inputs:
        repository: 'msh'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
  - job:
    steps:
    - script:
      displayName: artifacts    - 
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'